spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cocktail?createDatabaseIfNotExist=true
#    username: root
#    password: 3898
#    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  mail:
    host: smtp.gmail.com
    port: 465
    username: sukanto113@gmail.com
    password:
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
jwt:
  secretKey: t6pbutmIxWNzcK6vq7lVz2IfYWbNRyisScZOFe1sKbM=


