INSERT INTO category (id, name, picture) VALUES
(1, 'Whiskey-Based Cocktails', 'file/image/1 Whiskey Based Cocktails.png'),
(2, 'Gin-Based Cocktails', 'file/image/1 Gin Based Cocktails.png'),
(3, 'Vodka-Based Cocktails', 'file/image/1 Vodka Based Cocktails.png'),
(4, 'Rum-Based Cocktails', 'file/image/1 Rum-Based Cocktails.png'),
(5, 'Tequila-Based Cocktails', 'file/image/1 Tequila-Based Cocktails.png'),
(6, 'Brandy/Cognac-Based Cocktails', 'file/image/1 Brandy base.png');

INSERT INTO product (category_id, name, picture, ingredients, method) VALUES
(1, 'Old Fashioned', 'file/image/old fasiond.png', '2 oz Bourbon or Rye whiskey, 1 sugar cube, 2-3 dashes Angostura bitters, few dashes plain water', 'Muddle the sugar cube and bitters with one bar spoon of water at the bottom of a chilled rocks glass. Add whiskey and ice, stir until chilled. Garnish with an orange peel.'),
(1, 'Manhattan', 'file/image/Manhattan.png', '2 oz Rye or Bourbon, 1 oz Sweet Vermouth, 2 dashes Angostura bitters', 'Stir ingredients with ice, strain into a chilled cocktail glass. Garnish with a cherry.'),
(1, 'Whiskey Sour', 'file/image/Whiskey Sour.png', '2 oz Whiskey, 3/4 oz fresh lemon juice, 1/2 oz simple syrup, 1/2 oz egg white (optional)', 'Shake ingredients with ice, strain into a rocks glass over ice. Garnish with an orange slice and cherry.'),
(1, 'Mint Julep', 'file/image/Mint Julep.png', '2 oz Bourbon, 1 teaspoon powdered sugar, 2 teaspoons water, 4 mint leaves', 'Muddle mint leaves, sugar, and water in a glass. Fill the glass with ice, add Bourbon, and stir until the glass is frosted. Garnish with a mint sprig.'),
(1, 'Sazerac', 'file/image/Sazerac.png', '2 oz Rye whiskey, 1 sugar cube, 2 dashes Peychaud’s bitters, Absinthe rinse', 'Rinse a chilled old-fashioned glass with absinthe, discard excess. Muddle sugar cube and bitters, add whiskey and ice, stir. Strain into the prepared glass. Garnish with a lemon twist.'),
(1, 'Boulevardier', 'file/image/Boulevardier.png', '1.25 oz Bourbon or Rye, 1 oz Campari, 1 oz Sweet Vermouth', 'Stir ingredients with ice, strain into a rocks glass with ice. Garnish with an orange twist.'),
(2, 'Martini', 'file/image/Martini.png', '2.5 oz Gin, 0.5 oz Dry Vermouth', 'Stir ingredients with ice, strain into a chilled martini glass. Garnish with a lemon twist or olive.'),
(2, 'Negroni', 'file/image/Negroni.png', '1 oz Gin, 1 oz Campari, 1 oz Sweet Vermouth', 'Stir ingredients with ice, strain into a rocks glass over ice. Garnish with an orange peel.'),
(2, 'Tom Collins', 'file/image/Tom Collins.png', '2 oz Gin, 1 oz fresh lemon juice, 1/2 oz simple syrup, club soda', 'Shake gin, lemon juice, and syrup with ice, strain into a Collins glass over ice. Top with club soda. Garnish with a lemon wheel and cherry.'),
(2, 'French 75', 'file/image/French 75.png', '1 oz Gin, 1/2 oz fresh lemon juice, 1/2 oz simple syrup, Champagne', 'Shake gin, lemon juice, and syrup with ice, strain into a Champagne flute. Top with Champagne. Garnish with a lemon twist.'),
(2, 'Gin and Tonic', 'file/image/Gin and Tonic.png', '2 oz Gin, 4-6 oz Tonic water', 'Fill a highball glass with ice, add gin and tonic water. Garnish with a lime wedge.'),
(2, 'Gimlet', 'file/image/Gimlet.png', '2 oz Gin, 1 oz lime juice, 1/2 oz simple syrup', 'Shake ingredients with ice, strain into a chilled cocktail glass. Garnish with a lime wheel.'),
(3, 'Cosmopolitan', 'file/image/Cosmopolitan.png', '1.5 oz Vodka, 1 oz Cointreau, 1/2 oz fresh lime juice, 1/4 oz cranberry juice', 'Shake ingredients with ice, strain into a chilled martini glass. Garnish with a lime twist.'),
(3, 'Bloody Mary', 'file/image/Bloody Mary cocktail.png', '1.5 oz Vodka, 3 oz tomato juice, 1/2 oz lemon juice, 2 dashes Worcestershire sauce, 2 dashes hot sauce, pinch of salt and pepper', 'Roll ingredients back and forth with ice (do not shake), strain into an ice-filled highball glass. Garnish with celery stick and lemon wedge.'),
(3, 'Moscow Mule', 'file/image/Moscow Mule.png', '2 oz Vodka, 4-6 oz ginger beer, 1/2 oz fresh lime juice', 'Combine ingredients in a copper mug filled with ice, stir gently. Garnish with a lime wedge.'),
(3, 'Sea Breeze', 'file/image/Sea Breeze.png', '1.5 oz Vodka, 3 oz cranberry juice, 1 oz grapefruit juice', 'Build ingredients in a highball glass over ice, stir gently. Garnish with a lime wedge.'),
(3, 'Harvey Wallbanger', 'file/image/Harvey Wallbanger.png', '1.5 oz Vodka, 3 oz orange juice, 1/2 oz Galliano', 'Build vodka and orange juice in a highball glass over ice, float Galliano on top. Garnish with an orange slice.'),
(3, 'Black Russian', 'file/image/Bloody Mary cocktail.png', '1.5 oz Vodka, 3/4 oz coffee liqueur', 'Build ingredients in a rocks glass over ice, stir gently. No garnish.'),
(4, 'Mojito', 'file/image/.png', '2 oz White rum, 1/2 oz fresh lime juice, 1/2 oz simple syrup, 3 mint sprigs, soda water', 'Muddle mint, lime juice, and syrup in a glass, add rum and ice, top with soda water. Garnish with a mint sprig and lime wheel.'),
(4, 'Daiquiri', 'file/image/Mojito.png', '2 oz White rum, 1 oz fresh lime juice, 3/4 oz simple syrup', 'Shake ingredients with ice, strain into a chilled cocktail glass. Garnish with a lime wheel.'),
(4, 'Pina Colada', 'file/image/Pina Colada.png', '2 oz White rum, 1 oz coconut cream, 1 oz heavy cream, 6 oz fresh pineapple juice', 'Blend ingredients with ice until smooth, pour into a hurricane glass. Garnish with pineapple slice and cherry.'),
(4, 'Mai Tai', 'file/image/Mai Tai.png', '1.5 oz White rum, 3/4 oz fresh lime juice, 1/2 oz orange curaçao, 1/2 oz orgeat syrup, 1/2 oz dark rum (float)', 'Shake white rum, lime juice, orange curaçao, and orgeat syrup with ice, strain into an ice-filled glass, float dark rum on top, and garnish with a lime wheel and mint.'),
(5, 'Margarita', 'file/image/Margarita.png', '2 oz Tequila, 1 oz Cointreau, 1 oz fresh lime juice', 'Shake ingredients with ice, strain into a salt-rimmed rocks glass over ice. Garnish with a lime wheel.'),
(5, 'Tommy''s Margarita', 'file/image/Tommy_s Margarita.png', '2 oz Tequila, 1 oz fresh lime juice, 1/2 oz agave syrup', 'Shake ingredients with ice, strain into a salt-rimmed rocks glass over ice. Garnish with a lime wheel.'),
(5, 'Paloma', 'file/image/Paloma.png', '2 oz Tequila, 1/2 oz fresh lime juice, pinch of salt, grapefruit soda', 'Build tequila, lime juice, and salt in a highball glass over ice, top with grapefruit soda. Garnish with a lime wheel.'),
(5, 'Tequila Sunrise', 'file/image/Tequila Sunrise.png', '2 oz Tequila, 4 oz orange juice, 1/2 oz grenadine', 'Build tequila and orange juice in a highball glass over ice, slowly pour grenadine to create a sunrise effect. Garnish with an orange slice and cherry.'),
(6, 'Sidecar', 'file/image/Sidecar.png', '2 oz Cognac, 3/4 oz Cointreau, 3/4 oz fresh lemon juice', 'Shake ingredients with ice, strain into a sugar-rimmed cocktail glass. Garnish with a lemon twist.'),
(6, 'Brandy Alexander', 'file/image/Brandy Alexander.png', '1 oz Brandy, 1 oz dark crème de cacao, 1 oz cream', 'Shake ingredients with ice, strain into a chilled cocktail glass. Garnish with grated nutmeg.');
